#!/usr/bin/env python3

import requests
import click
import json

@click.command()
@click.option('--lookup', default='', help='print information about pokemon')
@click.option('--generation', default='', help='modifies set of moves returned by lookup')
@click.option('--move-type', 'movetype',default='', help='lists top 10 moves of move type')
def pokemon(lookup, generation, movetype):
    if lookup != '' and movetype == '':
       URL = "https://pokeapi.co/api/v2/pokemon/" + str(lookup)
       r = requests.get(URL).json()

       moves = []
       if generation == '':
           for move in r['moves']:
               moves.append(move['move']['name'])
           print(r['name'],  r['order'], moves)        
       else:
           for move in r['moves']:
               for detail in move['version_group_details']:
                   if generation in detail['version_group']['name']:
                       moves.append(move['move']['name'])
           print(r['name'], r['order'], moves)
    elif lookup == '' and movetype != '':
        URL = "https://pokeapi.co/api/v2/type/" + str(movetype)
        r = requests.get(URL).json()
        if generation == '':
            for move_id in range(10):
                print(r['moves'][move_id]['name'])
        else:
            moves = []
            move_id = 1
            #while len(moves) != 10:
            for i in range(10):
                # move_url = r['moves'][move_id]['url']
                URL2 = "https://pokeapi.co/api/v2/move/" + str(move_id)
                r2 = requests.get(URL2).json()
                move_generation = r2['generation']['name']
                if move_generation == generation:
                    moves.append(r['moves'][move_id - 1]['name'])
                move_id+=1
            print(moves)



            
if __name__ == "__main__":
    pokemon()
